name: ${project.name}
version: ${project.version}-${git.commit.id.abbrev}
description: ${project.description}
url: ${project.url}
main: hu.trigary.dragonhatchery.DragonHatcheryPlugin
api-version: 1.16

commands:
  dragonhatchery:
    description: "Interact and manage the ${project.name} plugin."
    permission: "dragonhatchery"
    permission-message: "§cYou do not have permission to use this command!"
