name: Build plugin (.jar)

on:
  push: # Make the new version downloadable whenever the plugin changes
    branches: [master] # Only make downloadable JARs from the stable branch
  schedule: # Uploaded artifacts expire after some time, so let's upload new ones every so often
    - cron: '0 0 1 * *' # Each month on the 1st at 00:00 (Once a month is the significant part)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn clean package
    - name: Determine project properties
      id: properties
      run: | # We can't just query `project.build.finalName` because the git hash gets evaluated as `null`
        echo ::set-output name=name::$(mvn help:evaluate -Dexpression="project.name" -q -DforceStdout)
        echo ::set-output name=version::$(mvn help:evaluate -Dexpression="project.version" -q -DforceStdout)
        echo ::set-output name=hash::$(git rev-parse --short HEAD)
    - name: Upload plugin (.jar)
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.properties.outputs.name }}-${{ steps.properties.outputs.version }}-${{ steps.properties.outputs.hash }}.jar
        path: target/${{ steps.properties.outputs.name }}-${{ steps.properties.outputs.version }}-${{ steps.properties.outputs.hash }}.jar
